server:
  port: 5000
  max-http-request-header-size: 102400

spring:
  datasource:
    url: jdbc:postgresql://edificad.com:5432/java?currentSchema=edificad
    username: sa
    password: root
    hikari:
      auto-commit: false
      pool-name: EdificadPoolConnections
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 60000
      validation-timeout: 3000
      initialization-fail-timeout: 5000
